server:
  port: 80

master:
  user:
    name: fordev
    email: fordev79@gmail.com
  
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/health
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      


  
  mail:
    host: smtp.gmail.com
    port: 587
    username: fordev79@gmail.com
    password: Hell0!@#
    properties:      mail:
        smtp:
          starttls:
            enable: true
